/**
 * This class is generated by jOOQ
 */
package org.jooq.util.repos.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.util.repos.Esjob;
import org.jooq.util.repos.Keys;
import org.jooq.util.repos.tables.records.TabJobTestRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabJobTest extends TableImpl<TabJobTestRecord> {

	private static final long serialVersionUID = 1672449197;

	/**
	 * The reference instance of <code>esjob.tab_job_test</code>
	 */
	public static final TabJobTest TAB_JOB_TEST = new TabJobTest();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TabJobTestRecord> getRecordType() {
		return TabJobTestRecord.class;
	}

	/**
	 * The column <code>esjob.tab_job_test.id</code>.
	 */
	public final TableField<TabJobTestRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>esjob.tab_job_test.location</code>.
	 */
	public final TableField<TabJobTestRecord, String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>esjob.tab_job_test.status</code>.
	 */
	public final TableField<TabJobTestRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(2), this, "");

	/**
	 * Create a <code>esjob.tab_job_test</code> table reference
	 */
	public TabJobTest() {
		this("tab_job_test", null);
	}

	/**
	 * Create an aliased <code>esjob.tab_job_test</code> table reference
	 */
	public TabJobTest(String alias) {
		this(alias, TAB_JOB_TEST);
	}

	private TabJobTest(String alias, Table<TabJobTestRecord> aliased) {
		this(alias, aliased, null);
	}

	private TabJobTest(String alias, Table<TabJobTestRecord> aliased, Field<?>[] parameters) {
		super(alias, Esjob.ESJOB, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TabJobTestRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TAB_JOB_TEST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TabJobTestRecord> getPrimaryKey() {
		return Keys.KEY_TAB_JOB_TEST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TabJobTestRecord>> getKeys() {
		return Arrays.<UniqueKey<TabJobTestRecord>>asList(Keys.KEY_TAB_JOB_TEST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TabJobTest as(String alias) {
		return new TabJobTest(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TabJobTest rename(String name) {
		return new TabJobTest(name, null);
	}
}
