/**
 * This class is generated by jOOQ
 */
package org.jooq.util.repos;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.util.repos.tables.TabJobTest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Esjob extends SchemaImpl {

	private static final long serialVersionUID = -564105437;

	/**
	 * The reference instance of <code>esjob</code>
	 */
	public static final Esjob ESJOB = new Esjob();

	/**
	 * No further instances allowed
	 */
	private Esjob() {
		super("esjob");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			TabJobTest.TAB_JOB_TEST);
	}
}
