/**
 * This class is generated by jOOQ
 */
package org.jooq.util.repos;


import javax.annotation.Generated;

import org.jooq.util.repos.tables.TabJobTest;


/**
 * Convenience access to all tables in esjob
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table esjob.tab_job_test
	 */
	public static final TabJobTest TAB_JOB_TEST = org.jooq.util.repos.tables.TabJobTest.TAB_JOB_TEST;
}
