/**
 * This class is generated by jOOQ
 */
package org.jooq.util.repos.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.util.repos.tables.TabJobTest;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabJobTestRecord extends UpdatableRecordImpl<TabJobTestRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = 1236363303;

	/**
	 * Setter for <code>esjob.tab_job_test.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>esjob.tab_job_test.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>esjob.tab_job_test.location</code>.
	 */
	public void setLocation(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>esjob.tab_job_test.location</code>.
	 */
	public String getLocation() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>esjob.tab_job_test.status</code>.
	 */
	public void setStatus(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>esjob.tab_job_test.status</code>.
	 */
	public String getStatus() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TabJobTest.TAB_JOB_TEST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TabJobTest.TAB_JOB_TEST.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TabJobTest.TAB_JOB_TEST.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TabJobTestRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TabJobTestRecord value2(String value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TabJobTestRecord value3(String value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TabJobTestRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TabJobTestRecord
	 */
	public TabJobTestRecord() {
		super(TabJobTest.TAB_JOB_TEST);
	}

	/**
	 * Create a detached, initialised TabJobTestRecord
	 */
	public TabJobTestRecord(Integer id, String location, String status) {
		super(TabJobTest.TAB_JOB_TEST);

		setValue(0, id);
		setValue(1, location);
		setValue(2, status);
	}
}
